<?php
    return array(
        'javascript' => 'JS/view',
        'news/edit/([0-9]+)' => 'news/edit/$1',
        'news/delete/([0-9]+)' => 'news/delete/$1',
        'news/write' => 'news/write',
        'news/add_comment/([0-9]+)' => 'news/add_com_db/$1',
        'news/edit_comment/([0-9]+)' => 'news/edit_com_db/$1',
        'news/delete_comment/([0-9]+)' => 'news/delete_com/$1',
        'news/([0-9]+)' => 'news/current_news/$1',
        'news' => 'news/view',
        'courses/delete/([0-9]+)' => 'courses/deleteCourse/$1',
        'task/delete/([0-9]+)' => 'task/deleteTask/$1',
        'task/edit/([0-9]+)' => 'task/editTask/$1',
        'courses/tjournal/([0-9]+)' => 'journal/teacherView/$1',
        'courses/sjournal/([0-9]+)' => 'journal/studentView/$1',
        'courses/([0-9]+)/add_task' => 'task/addTask/$1',
        'courses/([0-9]+)/ttask/([0-9]+)' => 'task/teacherCurrentTask/$1/$2',
        'courses/([0-9]+)/task/([0-9]+)' => 'task/currentTask/$1/$2',
        'courses/([0-9]+)' => 'courses/currentCourse/$1',
        'courses' => 'courses/view',
        '' => 'news/view',
        'profile/edit_profile' => 'user/editProfile',
        'user_rights' => 'user/right',
        'profile' => 'user/profile',
        'login' => 'user/login',
        'logout' => 'user/logout',
        'registration' => 'user/registration',
        'feedback' => 'messages/write',
        'comments' => 'news/comments',
        'message/([0-9]+)' => 'messages/view/$1',
        'message' => 'messages/view/1', 
        'languages' => 'language/create',
        'friends' => 'friends/view',
        'people' => 'friends/people',
        'plag' => 'plagiarism/view',
        'patterns' => 'patterns/view',
    );